

export const LOAD_PAIENTJOURNALS_SUCCESS = "LOAD_UNICORNS_SUCCESS";
export const CREATE_PAIENTJOURNALS_SUCCESS = "CREATE_UNICORN_SUCCESS";
export const UPDATED_PAIENTJOURNALS_SUCCESS = "UPDATED_UNICORN_SUCCESS";
export const DELETE_PAIENTJOURNALS_SUCCESS = "DELETE_UNICORN_SUCCESS";
