export const LOAD_PATIENTJOURNALS_SUCCESS = "LOAD_PATIENTJOURNALS_SUCCESS";
export const CREATE_PATENTJOURNAL_SUCCESS = "CREATE_PATENTJOURNAL_SUCCESS";
export const UPADE_PATENTJOURNAL_SUCCESS = "UPADE_PATENTJOURNAL_SUCCESS";
export const DELETE_PATENTJOURNAL_SUCCESS = "DELETE_PATENTJOURNAL_SUCCESS";